libctf: Remove undefined functions from ver. map
The functions ctf_label_set(), ctf_label_get(), ctf_arc_open(), ctf_fdopen(),
ctf_open(), ctf_bfdopen(), and ctf_bfdopen_ctfsect() are not defined. Their
inclusion in libctf/libctf.ver causes clang/llvm LTO optimizatiosn to fail with
error messages similar to

    error: version script assignment of LIBCTF_1.0 to symbol ctf_label_set
    failed: symbol not defined

This patch fixes the issue by removing the symbol names from libctf/libctf.ver

Fixes Gentoo bug 914640 (https://bugs.gentoo.org/914640)

Signed-off-by: Nicholas Vinson <nvinson234@gmail.com>