gprofng: PR29987 bfd/archive.c:1447: undefined reference to `filename_ncmp'
gprofng only depends on libopcodes but has been linked with libbfd and libiberty.
I removed unnecessary dependencies.
But the libbfd build has a side effect.
When I configure with --with-system-zlib and links my application with '../libbfd/libbfd.la -L ../libiberty -liberty',
my application will be linked with /usr/lib/liberty.a instead of ../libiberty/liberty.a
The problem is here:
% grep dependency_libs bfd/libbfd.la
dependency_libs=' -lz -L/usr/lib -lzstd /dev/shm/bld/libsframe/libsframe.la -ldl'
                      ^^^^^^^^^^^^^^^^^
                      |
  This is probably $(ZSTD_LIBS). Why is it not just -lzstd?

Please review my fixes in gprofng below.
Thank you,
-Vladimir

gprofng/ChangeLog
2023-01-12  Vladimir Mezentsev  <vladimir.mezentsev@oracle.com>

	PR gprofng/29987
	* configure.ac: Remove dependencies on libbfd and libiberty.
	* gprofng/src/Makefile.am: Likewise.
	* configure: Rebuild.
	* Makefile.in: Rebuild.
	* src/Makefile.in: Rebuild.
	* doc/Makefile.in: Rebuild.
	* gp-display-html/Makefile.in: Rebuild.