Gold/MIPS: Add targ_extra_size=64 for mips32 triples
So we can enable 64bit ELF support for MIPS32 toolchain.

This patch can fix build failure with configure:
   --target=mips-linux-gnu \
   --enable-targets=mips64-linux-gnuabi64,mips64-linux-gnuabin32
The error message is like:
   undefined reference to `gold::Output_data_reloc_base<9, true, 32, false>::
   ...